### ISSUE TITLE
Shader Problem Win 8 64Bit

### ISSUE THREAD

**Issue by marcelwirtz** [spsn/blocky-pc#1]
I downloaded the source today but can not get it run on my Windows 8 PC.

I see a window what is closing directly and get the following error in eclipse console, but can not find the mistake. Have not change anything.
## Info Log of Shader Object: 1

0(1) : error C0000: syntax error, unexpected type identifier, expecting '{' at token "mat4"

java.lang.RuntimeException: A compilation error occured in a shader.
    at ge.framework.shader.GL20Shader.createFromSource(GL20Shader.java:82)
    at ge.framework.shader.GL20Shader.<init>(GL20Shader.java:24)
    at ge.framework.shader.GL20Program.<init>(GL20Program.java:21)
    at ge.framework.shader.BasicProgram.<init>(BasicProgram.java:29)
    at ge.demo.game.Blocky.start(Blocky.java:238)
    at ge.demo.game.Blocky.main(Blocky.java:2525)

**Comment by spsn** [comment]
The GLSL code for the shaders contains qualifiers (highp, mediump, lowp) that are specific to OpenGL ES (so that the same shaders will work on the Raspberry Pi), but these are not recognised by all the OpenGL desktop implementations.

Have a look at the file ge.framework.shader.BasicProgram.java, and remove all the "highp" and "lowp". That should sort it out for you.  The same for the other *Program.java files.
